stack: node 18  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build:
  - webpack --config webpack.prod.js  # off - отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint

deploy:
  provider: GitHub
  auth_token:
    secure: p79ubl/WjoRQe/rxFspdFcY4ub1VEEeyZ3YRi1DKSYRQu51FBI5yXrxz84NZdO2Y
